# -*- coding: utf-8 -*-
"""files to import.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/190zmFqlQc8ZodhYd4CRKJx0w9ooiA3I9
"""

import json
import re
import num2words
import decimal
from decimal import Decimal
!pip install word2number
import word2number
from word2number import w2n