# -*- coding: utf-8 -*-
"""loading_input_json.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/190zmFqlQc8ZodhYd4CRKJx0w9ooiA3I9
"""

with open('/content/input.json','r') as input_file:
  input_data = json.load(input_file)
  input_file.close()
  input_data1=json.dumps(input_data , indent=6)
  input_data_self=json.dumps(input_data)