# -*- coding: utf-8 -*-
"""writing_output_json file.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/190zmFqlQc8ZodhYd4CRKJx0w9ooiA3I9
"""

def solution_dump(solution_file_path):
  solution_data = []
  #print(input_data1)
  for input_sentence in input_data1:
    print(input_sentence)
    solution_sid = int(input_sentence['sid'])
    print(solution_sid)
    solution_tokens = solution(input_sentence['output_tokens'])
    solution_data.append({'sid':solution_sid,
                          'output_tokens':solution_tokens})